# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PhonePack - Create Javascript apps for HTML5 and Cordova
email: wagnercsfilho@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Free and open source Javascript, HTML and CSS library for create Web and Mobile apps
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wagnercsfilho.github.io/phonepack" # the base hostname & protocol for your site
twitter_username: phonepackjs
github_username:  wagnercsfilho 


# Build settings
markdown: kramdown
